# fly.toml generated for frontend Vite app
app = "focus-financial"
primary_region = "bos"

[build]
  # Uses Dockerfile in root directory (make sure it builds frontend)

[http_service]
  internal_port = 80
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
